version: "3.8"

services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mycloudy
    ports:
      - "127.0.0.1:5432:5432"

  # fastapi:
  #   container_name: mycloudy_fastapi
  #   build: .
  #   depends_on:
  #     - db
  #   environment:
  #     DATABASE_URL: postgresql//root:root@127.0.0.1:5432/mycloudy
  #   ports:
  #     - "8000:8000"