"""Initial Migration without FK

Revision ID: 47957ecdec27
Revises: 
Create Date: 2025-06-27 19:52:19.091898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '47957ecdec27'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('InviteLinks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('linkToken', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('validTill', sa.DateTime(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('linkToken')
    )
    op.create_table('PasswordHash',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('salt', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('hash', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('firstName', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('lastName', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('lastLogin', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    op.drop_table('Roles')
    op.drop_table('PasswordHash')
    op.drop_table('InviteLinks')
    # ### end Alembic commands ###
