"""ondelete condition added to the tables

Revision ID: 4fd69ff9857f
Revises: 93893aa84b13
Create Date: 2025-07-02 10:27:20.354476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fd69ff9857f'
down_revision: Union[str, None] = '93893aa84b13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('InviteLinks_createdBy_fkey'), 'InviteLinks', type_='foreignkey')
    op.create_foreign_key(None, 'InviteLinks', 'Users', ['createdBy'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('PasswordHash_userId_fkey'), 'PasswordHash', type_='foreignkey')
    op.create_foreign_key(None, 'PasswordHash', 'Users', ['userId'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('Roles_createdBy_fkey'), 'Roles', type_='foreignkey')
    op.create_foreign_key(None, 'Roles', 'Users', ['createdBy'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Roles', type_='foreignkey')
    op.create_foreign_key(op.f('Roles_createdBy_fkey'), 'Roles', 'Users', ['createdBy'], ['id'])
    op.drop_constraint(None, 'PasswordHash', type_='foreignkey')
    op.create_foreign_key(op.f('PasswordHash_userId_fkey'), 'PasswordHash', 'Users', ['userId'], ['id'])
    op.drop_constraint(None, 'InviteLinks', type_='foreignkey')
    op.create_foreign_key(op.f('InviteLinks_createdBy_fkey'), 'InviteLinks', 'Users', ['createdBy'], ['id'])
    # ### end Alembic commands ###
