"""FKs added to tables

Revision ID: 93893aa84b13
Revises: 47957ecdec27
Create Date: 2025-06-27 19:53:23.132489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93893aa84b13'
down_revision: Union[str, None] = '47957ecdec27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('InviteLinks', sa.Column('createdBy', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'InviteLinks', 'Users', ['createdBy'], ['id'])
    op.add_column('PasswordHash', sa.Column('userId', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'PasswordHash', 'Users', ['userId'], ['id'])
    op.add_column('Roles', sa.Column('createdBy', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'Roles', 'Users', ['createdBy'], ['id'])
    op.add_column('Users', sa.Column('roleId', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'Users', 'Roles', ['roleId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='foreignkey')
    op.drop_column('Users', 'roleId')
    op.drop_constraint(None, 'Roles', type_='foreignkey')
    op.drop_column('Roles', 'createdBy')
    op.drop_constraint(None, 'PasswordHash', type_='foreignkey')
    op.drop_column('PasswordHash', 'userId')
    op.drop_constraint(None, 'InviteLinks', type_='foreignkey')
    op.drop_column('InviteLinks', 'createdBy')
    # ### end Alembic commands ###
