"""accepted removed and emailId added

Revision ID: d4192e52adc7
Revises: 4fd69ff9857f
Create Date: 2025-07-02 16:07:54.681537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd4192e52adc7'
down_revision: Union[str, None] = '4fd69ff9857f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('InviteLinks', sa.Column('emailId', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.drop_column('InviteLinks', 'accepted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('InviteLinks', sa.Column('accepted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('InviteLinks', 'emailId')
    # ### end Alembic commands ###
