"""Activity model updated with relevant fields and enums

Revision ID: 0e450e44a691
Revises: 259a9de6820b
Create Date: 2025-07-12 17:36:07.538025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e450e44a691'
down_revision: Union[str, Sequence[str], None] = '259a9de6820b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Activity', sa.Column('entityType', sa.String(length=20), nullable=False))
    op.add_column('Activity', sa.Column('timestamp', sa.DateTime(), nullable=False))
    op.alter_column('Activity', 'fileId',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('Activity', 'folderId',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('Activity', 'actionTime')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Activity', sa.Column('actionTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('Activity', 'folderId',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('Activity', 'fileId',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('Activity', 'timestamp')
    op.drop_column('Activity', 'entityType')
    # ### end Alembic commands ###
