"""New Model created folderShares to share the folder with users and ourself

Revision ID: 259a9de6820b
Revises: 30a9cca43350
Create Date: 2025-07-11 09:17:20.214673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '259a9de6820b'
down_revision: Union[str, Sequence[str], None] = '30a9cca43350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
