"""FKs added to the tables

Revision ID: 2e763b3c14de
Revises: 68ecfcad4a88
Create Date: 2025-07-17 01:36:28.916879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e763b3c14de'
down_revision: Union[str, Sequence[str], None] = '68ecfcad4a88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FolderTagLink',
    sa.Column('folderId', sa.Uuid(), nullable=False),
    sa.Column('tagId', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['folderId'], ['Folders.id'], ),
    sa.ForeignKeyConstraint(['tagId'], ['Tags.id'], ),
    sa.PrimaryKeyConstraint('folderId', 'tagId')
    )
    op.create_table('FileTagLink',
    sa.Column('fileId', sa.Uuid(), nullable=False),
    sa.Column('tagId', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['fileId'], ['Files.id'], ),
    sa.ForeignKeyConstraint(['tagId'], ['Tags.id'], ),
    sa.PrimaryKeyConstraint('fileId', 'tagId')
    )
    op.add_column('Activity', sa.Column('fileId', sa.Uuid(), nullable=True))
    op.add_column('Activity', sa.Column('folderId', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'Activity', 'Folders', ['folderId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'Activity', 'Files', ['fileId'], ['id'], ondelete='CASCADE')
    op.add_column('Files', sa.Column('folderId', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'Files', 'Folders', ['folderId'], ['id'], ondelete='CASCADE')
    op.add_column('RecentlyOpenedFiles', sa.Column('fileId', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'RecentlyOpenedFiles', 'Files', ['fileId'], ['id'], ondelete='CASCADE')
    op.add_column('Shares', sa.Column('fileId', sa.Uuid(), nullable=True))
    op.add_column('Shares', sa.Column('folderId', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'Shares', 'Files', ['fileId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'Shares', 'Folders', ['folderId'], ['id'], ondelete='CASCADE')
    op.add_column('VideoStreamInfo', sa.Column('fileId', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'VideoStreamInfo', 'Files', ['fileId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'VideoStreamInfo', type_='foreignkey')
    op.drop_column('VideoStreamInfo', 'fileId')
    op.drop_constraint(None, 'Shares', type_='foreignkey')
    op.drop_constraint(None, 'Shares', type_='foreignkey')
    op.drop_column('Shares', 'folderId')
    op.drop_column('Shares', 'fileId')
    op.drop_constraint(None, 'RecentlyOpenedFiles', type_='foreignkey')
    op.drop_column('RecentlyOpenedFiles', 'fileId')
    op.drop_constraint(None, 'Files', type_='foreignkey')
    op.drop_column('Files', 'folderId')
    op.drop_constraint(None, 'Activity', type_='foreignkey')
    op.drop_constraint(None, 'Activity', type_='foreignkey')
    op.drop_column('Activity', 'folderId')
    op.drop_column('Activity', 'fileId')
    op.drop_table('FileTagLink')
    op.drop_table('FolderTagLink')
    # ### end Alembic commands ###
