"""New Model created for recent opens of files

Revision ID: 30a9cca43350
Revises: 33c63fc1e0f4
Create Date: 2025-07-10 20:58:13.424847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30a9cca43350'
down_revision: Union[str, Sequence[str], None] = '33c63fc1e0f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RecentlyOpenedFiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fileId', sa.Uuid(), nullable=False),
    sa.Column('userId', sa.Uuid(), nullable=False),
    sa.Column('openedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fileId'], ['Files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RecentlyOpenedFiles')
    # ### end Alembic commands ###
