"""Changes in File Model added field tagId (nullable is True)

Revision ID: 33c63fc1e0f4
Revises: 837bbd0a831e
Create Date: 2025-07-09 13:12:44.536514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33c63fc1e0f4'
down_revision: Union[str, Sequence[str], None] = '837bbd0a831e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Files', sa.Column('tagId', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'Files', 'Tags', ['tagId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Files', type_='foreignkey')
    op.drop_column('Files', 'tagId')
    # ### end Alembic commands ###
