"""Tags and folder model updated with default color hex value

Revision ID: 340dc6f2e63b
Revises: 3c5adea9856d
Create Date: 2025-07-14 14:18:52.068700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '340dc6f2e63b'
down_revision: Union[str, Sequence[str], None] = '3c5adea9856d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
