"""Tags and folder model updated

Revision ID: 3c5adea9856d
Revises: 4f79cc1edb30
Create Date: 2025-07-14 13:39:19.226325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c5adea9856d'
down_revision: Union[str, Sequence[str], None] = '4f79cc1edb30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Folders', sa.Column('colorHex', sa.String(length=7), nullable=True))
    op.add_column('Tags', sa.Column('colorHex', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tags', 'colorHex')
    op.drop_column('Folders', 'colorHex')
    # ### end Alembic commands ###
