"""Tag model updated with new field and Folder,File, RecentlyOpenedFiles and Activity model updated

Revision ID: 4f79cc1edb30
Revises: b6d63cf65ed7
Create Date: 2025-07-14 01:40:28.604085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f79cc1edb30'
down_revision: Union[str, Sequence[str], None] = 'b6d63cf65ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('Activity_fileId_fkey'), 'Activity', type_='foreignkey')
    op.drop_constraint(op.f('Activity_folderId_fkey'), 'Activity', type_='foreignkey')
    op.create_foreign_key(None, 'Activity', 'Folders', ['folderId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'Activity', 'Files', ['fileId'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('Files_folderId_fkey'), 'Files', type_='foreignkey')
    op.drop_constraint(op.f('Files_tagId_fkey'), 'Files', type_='foreignkey')
    op.create_foreign_key(None, 'Files', 'Tags', ['tagId'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'Files', 'Folders', ['folderId'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('Folders_tagId_fkey'), 'Folders', type_='foreignkey')
    op.create_foreign_key(None, 'Folders', 'Tags', ['tagId'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('RecentlyOpenedFiles_fileId_fkey'), 'RecentlyOpenedFiles', type_='foreignkey')
    op.create_foreign_key(None, 'RecentlyOpenedFiles', 'Files', ['fileId'], ['id'], ondelete='CASCADE')
    op.add_column('Tags', sa.Column('isSystem', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tags', 'isSystem')
    op.drop_constraint(None, 'RecentlyOpenedFiles', type_='foreignkey')
    op.create_foreign_key(op.f('RecentlyOpenedFiles_fileId_fkey'), 'RecentlyOpenedFiles', 'Files', ['fileId'], ['id'])
    op.drop_constraint(None, 'Folders', type_='foreignkey')
    op.create_foreign_key(op.f('Folders_tagId_fkey'), 'Folders', 'Tags', ['tagId'], ['id'])
    op.drop_constraint(None, 'Files', type_='foreignkey')
    op.drop_constraint(None, 'Files', type_='foreignkey')
    op.create_foreign_key(op.f('Files_tagId_fkey'), 'Files', 'Tags', ['tagId'], ['id'])
    op.create_foreign_key(op.f('Files_folderId_fkey'), 'Files', 'Folders', ['folderId'], ['id'])
    op.drop_constraint(None, 'Activity', type_='foreignkey')
    op.drop_constraint(None, 'Activity', type_='foreignkey')
    op.create_foreign_key(op.f('Activity_folderId_fkey'), 'Activity', 'Folders', ['folderId'], ['id'])
    op.create_foreign_key(op.f('Activity_fileId_fkey'), 'Activity', 'Files', ['fileId'], ['id'])
    # ### end Alembic commands ###
