"""FKs added to tables

Revision ID: 501d03c223ac
Revises: d739b7c87e97
Create Date: 2025-06-27 20:46:28.873782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '501d03c223ac'
down_revision: Union[str, Sequence[str], None] = 'd739b7c87e97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Activity', sa.Column('fileId', sa.Uuid(), nullable=False))
    op.add_column('Activity', sa.Column('folderId', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'Activity', 'Files', ['fileId'], ['id'])
    op.create_foreign_key(None, 'Activity', 'Folders', ['folderId'], ['id'])
    op.add_column('FileShares', sa.Column('fileId', sa.Uuid(), nullable=False))
    op.add_column('FileShares', sa.Column('folderId', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'FileShares', 'Files', ['fileId'], ['id'])
    op.create_foreign_key(None, 'FileShares', 'Folders', ['folderId'], ['id'])
    op.add_column('Files', sa.Column('folderId', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'Files', 'Folders', ['folderId'], ['id'])
    op.add_column('Folders', sa.Column('tagId', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'Folders', 'Tags', ['tagId'], ['id'])
    op.add_column('VideoStreamInfo', sa.Column('fileId', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'VideoStreamInfo', 'Files', ['fileId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'VideoStreamInfo', type_='foreignkey')
    op.drop_column('VideoStreamInfo', 'fileId')
    op.drop_constraint(None, 'Folders', type_='foreignkey')
    op.drop_column('Folders', 'tagId')
    op.drop_constraint(None, 'Files', type_='foreignkey')
    op.drop_column('Files', 'folderId')
    op.drop_constraint(None, 'FileShares', type_='foreignkey')
    op.drop_constraint(None, 'FileShares', type_='foreignkey')
    op.drop_column('FileShares', 'folderId')
    op.drop_column('FileShares', 'fileId')
    op.drop_constraint(None, 'Activity', type_='foreignkey')
    op.drop_constraint(None, 'Activity', type_='foreignkey')
    op.drop_column('Activity', 'folderId')
    op.drop_column('Activity', 'fileId')
    # ### end Alembic commands ###
