"""Added self referencing parentId in folders

Revision ID: 669e708c852f
Revises: 501d03c223ac
Create Date: 2025-07-07 23:57:02.422359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '669e708c852f'
down_revision: Union[str, Sequence[str], None] = '501d03c223ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Folders', sa.Column('parentId', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'Folders', 'Folders', ['parentId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Folders', type_='foreignkey')
    op.drop_column('Folders', 'parentId')
    # ### end Alembic commands ###
