"""Initial migration

Revision ID: 68ecfcad4a88
Revises: 
Create Date: 2025-07-17 01:26:54.302508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '68ecfcad4a88'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Activity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('userId', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entityType', sa.String(length=20), nullable=False),
    sa.Column('fieldChanged', sa.String(length=50), nullable=True),
    sa.Column('oldValue', sa.Text(), nullable=True),
    sa.Column('newValue', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('fileName', sa.Text(), nullable=False),
    sa.Column('fileExtension', sa.String(length=10), nullable=False),
    sa.Column('fileSize', sa.BigInteger(), nullable=False),
    sa.Column('filePath', sa.Text(), nullable=False),
    sa.Column('fileType', sa.String(length=20), nullable=False),
    sa.Column('lastModified', sa.DateTime(), nullable=False),
    sa.Column('totalVideoLength', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Folders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('folderPath', sa.Text(), nullable=True),
    sa.Column('parentId', sa.Uuid(), nullable=True),
    sa.Column('createdBy', sa.Uuid(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('isSystem', sa.Boolean(), nullable=False),
    sa.Column('colorHex', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['parentId'], ['Folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RecentlyOpenedFiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('userId', sa.Uuid(), nullable=False),
    sa.Column('openedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Shares',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sharedWithUserId', sa.Uuid(), nullable=True),
    sa.Column('sharedByUserId', sa.Uuid(), nullable=False),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('sharedAt', sa.DateTime(), nullable=False),
    sa.Column('isPublic', sa.Boolean(), nullable=False),
    sa.Column('accessToken', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expiresAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('createdBy', sa.Uuid(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('isSystem', sa.Boolean(), nullable=False),
    sa.Column('colorHex', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('VideoStreamInfo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('userId', sa.Uuid(), nullable=False),
    sa.Column('currentTrackAt', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('VideoStreamInfo')
    op.drop_table('Tags')
    op.drop_table('Shares')
    op.drop_table('RecentlyOpenedFiles')
    op.drop_table('Folders')
    op.drop_table('Files')
    op.drop_table('Activity')
    # ### end Alembic commands ###
