"""folderPath added to Folders model

Revision ID: 75eb6dedcd41
Revises: cdce13b4664b
Create Date: 2025-07-16 13:40:27.598573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75eb6dedcd41'
down_revision: Union[str, Sequence[str], None] = 'cdce13b4664b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Folders', sa.Column('folderPath', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Folders', 'folderPath')
    # ### end Alembic commands ###
