"""Changes in Tags Model fields and added new field description

Revision ID: 837bbd0a831e
Revises: fa923c65eb98
Create Date: 2025-07-09 12:48:38.568049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '837bbd0a831e'
down_revision: Union[str, Sequence[str], None] = 'fa923c65eb98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tags', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    op.alter_column('Tags', 'createdBy',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Tags', 'createdBy',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('Tags', 'description')
    # ### end Alembic commands ###
