"""Oncascade condition added to FKs in models

Revision ID: 9103f60fe9eb
Revises: 75eb6dedcd41
Create Date: 2025-07-16 17:27:00.236137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9103f60fe9eb'
down_revision: Union[str, Sequence[str], None] = '75eb6dedcd41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('FileShares_folderId_fkey'), 'FileShares', type_='foreignkey')
    op.drop_constraint(op.f('FileShares_fileId_fkey'), 'FileShares', type_='foreignkey')
    op.create_foreign_key(None, 'FileShares', 'Folders', ['folderId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'FileShares', 'Files', ['fileId'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('FolderShares_folderId_fkey'), 'FolderShares', type_='foreignkey')
    op.create_foreign_key(None, 'FolderShares', 'Folders', ['folderId'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('VideoStreamInfo_fileId_fkey'), 'VideoStreamInfo', type_='foreignkey')
    op.create_foreign_key(None, 'VideoStreamInfo', 'Files', ['fileId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'VideoStreamInfo', type_='foreignkey')
    op.create_foreign_key(op.f('VideoStreamInfo_fileId_fkey'), 'VideoStreamInfo', 'Files', ['fileId'], ['id'])
    op.drop_constraint(None, 'FolderShares', type_='foreignkey')
    op.create_foreign_key(op.f('FolderShares_folderId_fkey'), 'FolderShares', 'Folders', ['folderId'], ['id'])
    op.drop_constraint(None, 'FileShares', type_='foreignkey')
    op.drop_constraint(None, 'FileShares', type_='foreignkey')
    op.create_foreign_key(op.f('FileShares_fileId_fkey'), 'FileShares', 'Files', ['fileId'], ['id'])
    op.create_foreign_key(op.f('FileShares_folderId_fkey'), 'FileShares', 'Folders', ['folderId'], ['id'])
    # ### end Alembic commands ###
