"""parent folder name field added to activity model

Revision ID: b448d2a358d6
Revises: ea1101042e1d
Create Date: 2025-07-17 13:44:38.872526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b448d2a358d6'
down_revision: Union[str, Sequence[str], None] = 'ea1101042e1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Activity', sa.Column('parentFolderName', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Activity', 'parentFolderName')
    # ### end Alembic commands ###
