"""Activity model updated with new fieldChanged attribute

Revision ID: b6d63cf65ed7
Revises: 0e450e44a691
Create Date: 2025-07-13 13:46:13.712782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6d63cf65ed7'
down_revision: Union[str, Sequence[str], None] = '0e450e44a691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Activity', sa.Column('fieldChanged', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Activity', 'fieldChanged')
    # ### end Alembic commands ###
