"""FKs added to the tables

Revision ID: cdce13b4664b
Revises: eddc76c21215
Create Date: 2025-07-16 13:36:33.302473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdce13b4664b'
down_revision: Union[str, Sequence[str], None] = 'eddc76c21215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FileShares', sa.Column('fileId', sa.Uuid(), nullable=False))
    op.add_column('FileShares', sa.Column('folderId', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'FileShares', 'Files', ['fileId'], ['id'])
    op.create_foreign_key(None, 'FileShares', 'Folders', ['folderId'], ['id'])
    op.add_column('Files', sa.Column('folderId', sa.Uuid(), nullable=False))
    op.add_column('Files', sa.Column('tagId', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'Files', 'Tags', ['tagId'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'Files', 'Folders', ['folderId'], ['id'], ondelete='CASCADE')
    op.add_column('FolderShares', sa.Column('folderId', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'FolderShares', 'Folders', ['folderId'], ['id'])
    op.add_column('Folders', sa.Column('parentId', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'Folders', 'Folders', ['parentId'], ['id'])
    op.add_column('RecentlyOpenedFiles', sa.Column('fileId', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'RecentlyOpenedFiles', 'Files', ['fileId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'RecentlyOpenedFiles', type_='foreignkey')
    op.drop_column('RecentlyOpenedFiles', 'fileId')
    op.drop_constraint(None, 'Folders', type_='foreignkey')
    op.drop_column('Folders', 'parentId')
    op.drop_constraint(None, 'FolderShares', type_='foreignkey')
    op.drop_column('FolderShares', 'folderId')
    op.drop_constraint(None, 'Files', type_='foreignkey')
    op.drop_constraint(None, 'Files', type_='foreignkey')
    op.drop_column('Files', 'tagId')
    op.drop_column('Files', 'folderId')
    op.drop_constraint(None, 'FileShares', type_='foreignkey')
    op.drop_constraint(None, 'FileShares', type_='foreignkey')
    op.drop_column('FileShares', 'folderId')
    op.drop_column('FileShares', 'fileId')
    # ### end Alembic commands ###
