"""Initial Migration without FK

Revision ID: d739b7c87e97
Revises: 
Create Date: 2025-06-27 20:45:42.622051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd739b7c87e97'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Activity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('userId', sa.Uuid(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('oldValue', sa.Text(), nullable=True),
    sa.Column('newValue', sa.Text(), nullable=True),
    sa.Column('actionTime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('FileShares',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sharedWithUserId', sa.Uuid(), nullable=False),
    sa.Column('sharedByUserId', sa.Uuid(), nullable=False),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('sharedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('fileName', sa.Text(), nullable=False),
    sa.Column('fileExtension', sa.String(length=10), nullable=False),
    sa.Column('fileSize', sa.BigInteger(), nullable=False),
    sa.Column('filePath', sa.Text(), nullable=False),
    sa.Column('fileType', sa.String(length=20), nullable=False),
    sa.Column('lastModified', sa.DateTime(), nullable=False),
    sa.Column('totalVideoLength', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Folders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('createdBy', sa.Uuid(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('createdBy', sa.Uuid(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('VideoStreamInfo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('userId', sa.Uuid(), nullable=False),
    sa.Column('currentTrackAt', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('VideoStreamInfo')
    op.drop_table('Tags')
    op.drop_table('Folders')
    op.drop_table('Files')
    op.drop_table('FileShares')
    op.drop_table('Activity')
    # ### end Alembic commands ###
