"""parent id added to activity model

Revision ID: ea1101042e1d
Revises: d7f01c4ee3e1
Create Date: 2025-07-17 12:57:29.068605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea1101042e1d'
down_revision: Union[str, Sequence[str], None] = 'd7f01c4ee3e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Activity', sa.Column('parentId', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'Activity', 'Folders', ['parentId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Activity', type_='foreignkey')
    op.drop_column('Activity', 'parentId')
    # ### end Alembic commands ###
