"""name added to activity model and softDeleted added to File and Folder model

Revision ID: f13fef5f9bbd
Revises: b448d2a358d6
Create Date: 2025-07-17 16:02:08.438667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f13fef5f9bbd'
down_revision: Union[str, Sequence[str], None] = 'b448d2a358d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Activity', sa.Column('fileType', sa.String(length=20), nullable=True))
    op.add_column('Activity', sa.Column('fileName', sa.Text(), nullable=True))
    op.add_column('Files', sa.Column('softDeleted', sa.Boolean(), nullable=False))
    op.add_column('Folders', sa.Column('softDeleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Folders', 'softDeleted')
    op.drop_column('Files', 'softDeleted')
    op.drop_column('Activity', 'fileName')
    op.drop_column('Activity', 'fileType')
    # ### end Alembic commands ###
