"""Changes in Folders Model fields and added new one

Revision ID: fa923c65eb98
Revises: 669e708c852f
Create Date: 2025-07-09 11:23:10.186783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa923c65eb98'
down_revision: Union[str, Sequence[str], None] = '669e708c852f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Folders', sa.Column('isSystem', sa.Boolean(), nullable=False))
    op.alter_column('Folders', 'createdBy',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Folders', 'createdBy',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('Folders', 'isSystem')
    # ### end Alembic commands ###
