"""Tags model updated with new field updatedAt

Revision ID: faa896f22950
Revises: 340dc6f2e63b
Create Date: 2025-07-14 14:35:49.235637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faa896f22950'
down_revision: Union[str, Sequence[str], None] = '340dc6f2e63b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tags', sa.Column('updatedAt', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tags', 'updatedAt')
    # ### end Alembic commands ###
